version: "2"
linters:
  enable:
    - bodyclose
    - gosec
    - nilerr
    - revive
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
